### ISSUE TITLE
Enum vs String

### ISSUE THREAD

**Issue by delaneyj** [kelindar/column#101]
In the million example you use enum for all string like fields.  For things with a low cardinality, like gender, it makes sense but you also did it for names. Is there any more documentation or guidance on when to use each?

**Comment by Dreeseaw** [comment]
Under the hood, an enum maps a uint32 to a string for storage & filtering. Therefore, I'd error on the side of using enums for low to mid cardinality columns, and even benchmarking them against strings in higher-cardinality use cases
