### ISSUE TITLE
Different results from query

### ISSUE THREAD

**Issue by kempjeng** [kelindar/column#17]
When I query with `WithValue` or `WithString` I'm able to return different results.

    func TestQuery(t *testing.T) {
    	model := column.NewCollection()
    	model.CreateColumnsOf(map[string]interface{}{
    		"ID": "",
    	})
    
    	model.Query(func(txn *column.Txn) error {
    		for i := 0; i < 20000; i++ {
    
    			txt := fmt.Sprint(i)
    			txn.Insert(map[string]interface{}{
    				"ID": txt,
    			})
    		}
    		return nil
    	})
    
    	model.Query(func(txn *column.Txn) error {
    		fmt.Println(txn.WithValue("ID", func(v interface{}) bool {
    			return v.(string) == "5"
    		}).Count())
    		fmt.Println(txn.WithString("ID", func(v string) bool {
    			return v == "5"
    		}).Count())
    		return nil
    	})
    }
    
The problem gets more pronounced the higher the loop count.  For example, at 10,000 there are no issues, but at 1,000,000 there are 62.  The first instance happens at 16,390 loops

Changing the txt format to `txt := fmt.Sprintf("%2d", i)` removes the problem ( I tried up to 100,000,000 iterations)

I noted this problem when generating with uuid's, the example above is just simpler to generate

**Comment by kelindar** [comment]
@kempjeng I fixed the bug with `WithValue()` (see #18). Would you be able to check if this is still happening for you?

**Comment by kempjeng** [comment]
confirmed it's fixed, thanks
