### ISSUE TITLE
Can Collection object be serialized?

### ISSUE THREAD

**Issue by didip** [kelindar/column#33]
I am thinking of serializing it into BadgerDB. Is there a safe mechanism to do so?

**Comment by kelindar** [comment]
Snapshots aren't supported right now, but I've been thinking of implementing it. Only thing supported is CDC via a transaction commit log, which can be used for durability purposes and replayed to create a read replica. 

Do keep in mind tho, the API of this project isn't stable yet and will change in the future (guaranteed) - hence it's not yet versioned.

**Comment by kelindar** [comment]
Fyi, I merged the snapshotting today (see https://github.com/kelindar/column/pull/39), there's still some work to be done to merge/reconcile incomplete transactions in case the snapshot happens concurrently with new writes, but most of the stuff should work.
