### ISSUE TITLE
Background reading?

### ISSUE THREAD

**Issue by adwelly** [kelindar/column#34]
This is a fascinating area, but somewhat obscure. Are there any papers or books you could recommend for someone trying to get a broad understanding of column stores in general and Kelindar in particular?

**Comment by kelindar** [comment]
I found a couple of papers useful while implementing this:

* [Decomposition Storage Model](https://www.inf.ufpr.br/eduardo/ensino/ci809/papers/DSM-columns.pdf), 1985, Copeland and Khoshafian
* [The Design and Implementation of Modern Column-Oriented Database Systems](https://stratos.seas.harvard.edu/files/stratos/files/columnstoresfntdbs.pdf), 2013, D. Abadi et al

For the design of this specific library, I suggest you read the source code as I don't have anything else available.
