### ISSUE TITLE
ForKind should return an error instead of panicing

### ISSUE THREAD

**Issue by lukasmalkmus** [kelindar/column#38]
The `ForKind` function panics for an unknown column type: https://github.com/kelindar/column/blob/1f327b4accfd481c49c59cd478fb63d3de5f7313/column.go#L115

But it would be nicer if it would error and be picked up by: https://github.com/kelindar/column/blob/1f327b4accfd481c49c59cd478fb63d3de5f7313/collection.go#L230

**Comment by kelindar** [comment]
Added in the last PR https://github.com/kelindar/column/pull/39
